# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Workflow syntax for GitHub Actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# Context and expression syntax for GitHub Actions
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

# push only, not merge
name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.5]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install gperf -y
      - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - run: mkdir chromium
      - run: cd chromium && ../depot_tools/fetch --no-history chromium
      - run: cp remove-ext-csp-restriction.patch chromium/src
      - run: cd chromium/src && git apply remove-ext-csp-restriction.patch && ../../build.sh
